/** @type {import('tailwindcss').Config} */
export default {
    content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
    theme: {
        extend: {
            boxShadow: {
                "custom-inner": "inset 0px -3px 4px 0px rgba(136, 136, 136, 0.25)",
                illuminated: "0 4px 20px 0 rgba(255, 255, 255, 0.25)",
            },
            screens: {
                md: "880px",
                lg: "1090px",
                custom: "1920px",
                "2xl": "1440px",
                "h-sm": { raw: "(min-height: 640px)" },
                "h-md": { raw: "(min-height: 768px)" },
                "h-lg": { raw: "(min-height: 1024px)" },
                "h-xl": { raw: "(min-height: 1280px)" },
            },
            colors: {
                beige: "#F3F3F1",
                beige_dark: "#D9D9D7",
                smoke: "#9C9C9A",
                smoke_dark: "#171717",
                pink_light: "#FFEDF5",
                pink_mid: "#F588B9",
                pink_dark: "#D6699A",
                cod_black: "#262625",
                green_mid: "#A2B87E",
                green_dark: "#95AE6D",
                green_light: "#ECFFCE",
                cod_white: "#FEFEFE",
                blue_dark: "#6B93C0",
                blue_light: "#BADAFF",
                mustard_dark: "#C2BB82",
                mustard_light: "#FFFAC2",
                mustard_mid: "#CAC48E",
                orange_mid: "#F28164",
                orange_light: "#FFBCAB",
                orange_dark: "#D46F55",
                purple_dark: "#8A92E3",
                purple_light: "#EBEDFF",
                purple_mid: "#9FA8FE",
                gray: "#9B9B9B",
            },
            keyframes: {
                textAnimationLeft: {
                    "0%": { left: "15%", transform: "translate(-50%, -90%)", opacity: "0" },
                    "25%": { left: "50%", transform: "translate(-50%, -90%)", opacity: "1" },
                    "75%": { left: "50%", transform: "translate(-50%, -90%)", opacity: "1" },
                    "100%": { left: "85%", transform: "translate(-50%, -90%)", opacity: "0" },
                },
                textAnimationRight: {
                    "0%": { right: "15%", transform: "translate(50%, 90%)", opacity: "0" },
                    "25%": { right: "50%", transform: "translate(50%, 90%)", opacity: "1" },
                    "75%": { right: "50%", transform: "translate(50%, 90%)", opacity: "1" },
                    "100%": { right: "85%", transform: "translate(50%, 90%)", opacity: "0" },
                },
                textAnimationVs: {
                    "0%": { opacity: "0", transform: "translate(0, 0)" },
                    "10%": { opacity: "1", transform: "translate(0, 0)" },
                    "90%": { opacity: "1", transform: "translate(0, 0)" },
                    "100%": { opacity: "0", transform: "translate(0, 0)" },
                },
                moveAndShrink: {
                    "0%": { transform: "translate(0, 0) scale(2)", opacity: "1" },
                    "100%": {
                        transform: "translate(0, var(--target-y)) scale(0.19)",
                    },
                },
                fightBanner: {
                    "0%": { transform: "scale(3)", opacity: "0" },
                    "80%": { transform: "scale(2)", opacity: "1" },
                    "100%": { transform: "scale(2)", opacity: "0" },
                },
                fadeOut: {
                    "0%": { opacity: "1" },
                    "100%": { opacity: "0" },
                },
                "move-random": {
                    "0%": { transform: "translate(0, 0)", opacity: "1" },
                    "100%": {
                        transform: "translate(calc(-1 * var(--random-x)), calc(-1 * var(--random-y)))",
                        opacity: "0",
                    },
                },
            },
            animation: {
                "text-move-left": "textAnimationLeft 3s ease-in-out 0.25s forwards",
                "text-move-right": "textAnimationRight 3s ease-in-out 0.25s forwards",
                "vs-appear": "textAnimationVs 2.3s ease-in-out 0.6s forwards",
                moveAndShrink: "moveAndShrink 1.5s ease-out forwards",
                fight: "fightBanner 1s ease-out forwards",
                "fade-out": "fadeOut 0.6s ease-in-out forwards",
                "move-random": "move-random 1s ease-out forwards",
            },
        },
    },
    safelist: [
        "bg-beige",
        "bg-beige_dark",
        "bg-smoke",
        "bg-smoke_dark",
        "bg-pink_light",
        "bg-pink_mid",
        "bg-pink_dark",
        "bg-cod_black",
        "bg-green_mid",
        "bg-green_dark",
        "bg-green_light",
        "bg-cod_white",
        "bg-blue_dark",
        "bg-blue_light",
        "bg-mustard_dark",
        "bg-mustard_light",
        "bg-mustard_mid",
        "bg-orange_mid",
        "bg-orange_light",
        "bg-orange_dark",
        "bg-purple_dark",
        "bg-purple_light",
        "bg-purple_mid",
        "text-beige",
        "text-beige_dark",
        "text-smoke",
        "text-smoke_dark",
        "text-pink_light",
        "text-pink_mid",
        "text-pink_dark",
        "text-cod_black",
        "text-green_mid",
        "text-green_dark",
        "text-green_light",
        "text-cod_white",
        "text-blue_dark",
        "text-blue_light",
        "text-mustard_dark",
        "text-mustard_light",
        "text-mustard_mid",
        "text-orange_mid",
        "text-orange_light",
        "text-orange_dark",
        "text-purple_dark",
        "text-purple_light",
        "text-purple_mid",
        "stroke-green_light",
        "stroke-orange_light",
        "stroke-beige",
        "stroke-red-600",
    ],
    plugins: [],
    darkMode: ["class", '[data-theme="dark"]'],
};
